// ========================================
// KYDNO KORE - ADMIN PANEL TABS
// UI ONLY - DOES NOT CHANGE ADMIN FUNCTIONS
// ========================================

document.addEventListener("DOMContentLoaded", () => {

    const codesTab = document.getElementById("admin-tab-codes");
        const petDeleteTab = document.getElementById("admin-tab-pet-delete");
            const petAddTab = document.getElementById("admin-tab-pet-add");
                const kashTab = document.getElementById("admin-tab-kash");

                    const codesSection =
                            document.getElementById("admin-codes-section");

                                const kashSection =
                                        document.getElementById("admin-kash-controls");

                                            const inventoryPopup =
                                                    document.getElementById("admin-inventory-popup");

                                                        const addItemPopup =
                                                                document.getElementById("admin-add-item-popup");

                                                                    const searchText =
                                                                            document.getElementById("admin-user-search");

                                                                                const searchButton =
                                                                                        document.getElementById("admin-search-button");

                                                                                            const searchResult =
                                                                                                    document.getElementById("admin-user-result");


                                                                                                        function closeAllAdminPopups() {

                                                                                                                if (inventoryPopup) {
                                                                                                                            inventoryPopup.classList.add("hidden");
                                                                                                                                    }

                                                                                                                                            if (addItemPopup) {
                                                                                                                                                        addItemPopup.classList.add("hidden");
                                                                                                                                                                }

                                                                                                                                                                    }


                                                                                                                                                                        function showCodes() {

                                                                                                                                                                                closeAllAdminPopups();

                                                                                                                                                                                        if (codesSection) {
                                                                                                                                                                                                    codesSection.style.display = "block";
                                                                                                                                                                                                            }

                                                                                                                                                                                                                    if (kashSection) {
                                                                                                                                                                                                                                kashSection.style.display = "none";
                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                if (searchText) {
                                                                                                                                                                                                                                                            searchText.style.display = "none";
                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                            if (searchButton) {
                                                                                                                                                                                                                                                                                        searchButton.style.display = "none";
                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                        if (searchResult) {
                                                                                                                                                                                                                                                                                                                    searchResult.style.display = "none";
                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                }


                                                                                                                                                                                                                                                                                                                                    function showKash() {

                                                                                                                                                                                                                                                                                                                                            closeAllAdminPopups();

                                                                                                                                                                                                                                                                                                                                                    if (codesSection) {
                                                                                                                                                                                                                                                                                                                                                                codesSection.style.display = "none";
                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                if (kashSection) {
                                                                                                                                                                                                                                                                                                                                                                                            kashSection.style.display = "block";
                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                            if (searchText) {
                                                                                                                                                                                                                                                                                                                                                                                                                        searchText.style.display = "";
                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                        if (searchButton) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    searchButton.style.display = "";
                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (searchResult) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                searchResult.style.display = "";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                function showPetDelete() {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        closeAllAdminPopups();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (codesSection) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            codesSection.style.display = "none";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (kashSection) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        kashSection.style.display = "none";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (searchText) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    searchText.style.display = "";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (searchButton) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                searchButton.style.display = "";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (searchResult) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            searchResult.style.display = "";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            function showPetAdd() {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    closeAllAdminPopups();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (codesSection) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        codesSection.style.display = "none";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (kashSection) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    kashSection.style.display = "none";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (searchText) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                searchText.style.display = "";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (searchButton) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            searchButton.style.display = "";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (searchResult) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        searchResult.style.display = "";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (codesTab) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                codesTab.addEventListener("click", showCodes);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (petDeleteTab) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                petDeleteTab.addEventListener("click", showPetDelete);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (petAddTab) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                petAddTab.addEventListener("click", showPetAdd);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (kashTab) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                kashTab.addEventListener("click", showKash);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Start with Codes visible.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            showCodes();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
