// ========================================
// KYDNO KORE - ADMIN CODES
// ========================================

document.addEventListener("DOMContentLoaded", () => {
  const createButton = document.getElementById("admin-create-code");

  const codeInput = document.getElementById("admin-code-name");

  const rewardInput = document.getElementById("admin-code-reward");

  const limitInput = document.getElementById("admin-code-limit");

  const status = document.getElementById("admin-code-status");

  const codesSection = document.getElementById("admin-codes-section");

  if (
    !createButton ||
    !codeInput ||
    !rewardInput ||
    !limitInput ||
    !status ||
    !codesSection
  ) {
    console.warn("Admin Codes elements not found.");
    return;
  }
  let codeList = document.getElementById("admin-code-list");

  if (!codeList) {
    codeList = document.createElement("div");

    codeList.id = "admin-code-list";

    codeList.style.marginTop = "18px";

    codesSection.appendChild(codeList);
  }

  function escapeHtml(value) {
    return String(value)
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;")
      .replace(/'/g, "&#039;");
  }
  async function loadCodes() {
    codeList.innerHTML = `
                            <div style="
                                            padding:14px;
                                                            text-align:center;
                                                                            opacity:.7;
                                                                                        ">
                                                                                                        Loading Codes...
                                                                                                                    </div>
                                                                                                                            `;

    try {
      const { data, error } = await supabaseClient.rpc("admin_get_kash_codes");

      if (error) {
        console.error("Admin code list error:", error);

        codeList.innerHTML = `
            <div style="
                    padding:14px;
                            color:#ff7777;
                                ">
                                        Unable to load codes: ${escapeHtml(error.message)}
                                            </div>
                                            `;

        return;
      }

      if (!Array.isArray(data) || data.length === 0) {
        codeList.innerHTML = `
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style="
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                padding:14px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        text-align:center;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                opacity:.65;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            No codes created yet.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                `;

        return;
      }
      codeList.innerHTML = "";

      data.forEach((code) => {
        const card = document.createElement("div");

        card.style.marginBottom = "10px";

        card.style.padding = "14px";

        card.style.border = "1px solid rgba(212,175,55,.35)";

        card.style.borderRadius = "12px";

        card.style.background = "rgba(10,18,32,.75)";

        const claimed = Number(code.redemption_count) || 0;

        const maximum = Number(code.max_redemptions) || 0;

        const reward = Number(code.reward_kash) || 0;

        const active = code.is_active === true;

        card.innerHTML = `
                                                                                                                                                                                                                                                                                                                                                                                                                                     <div style="
                                                                                                                                                                                                                                                                                                                                                                                                                                                             display:flex;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     justify-content:space-between;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             align-items:center;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     gap:10px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             margin-bottom:8px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <strong style="
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     font-size:16px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 color:#f4d77a;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ${escapeHtml(code.code)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             </strong>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     <span style="
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 font-size:11px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             padding:4px 8px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         border-radius:8px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     background:${
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       active
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ? "rgba(70,200,120,.15)"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         : "rgba(200,70,70,.15)"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 color:${
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   active
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ? "#69e09a"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     : "#ff7777"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ${active ? "ACTIVE" : "INACTIVE"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             </span>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 `;
        card.innerHTML += `
                                      <div style="
                                                              display:grid;
                                                                                      grid-template-columns:repeat(2, 1fr);
                                                                                                              gap:8px;
                                                                                                                                  ">
                                                                                                                                  
                                                                                                                                                          <div style="
                                                                                                                                                                                      padding:9px;
                                                                                                                                                                                                                  border-radius:8px;
                                                                                                                                                                                                                                              background:rgba(255,255,255,.04);
                                                                                                                                                                                                                                                                      ">
                                                                                                                                                                                                                                                                                                  <div style="
                                                                                                                                                                                                                                                                                                                                  font-size:10px;
                                                                                                                                                                                                                                                                                                                                                                  opacity:.55;
                                                                                                                                                                                                                                                                                                                                                                                                  margin-bottom:3px;
                                                                                                                                                                                                                                                                                                                                                                                                                              ">
                                                                                                                                                                                                                                                                                                                                                                                                                                                              REWARD
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div style="
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      font-weight:bold;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ${reward.toLocaleString()} Kash
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div style="
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          padding:9px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      border-radius:8px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  background:rgba(255,255,255,.04);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div style="
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      font-size:10px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      opacity:.55;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      margin-bottom:3px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  CLAIMS
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div style="
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          font-weight:bold;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ${claimed} / ${maximum}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div style="
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          margin-top:8px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  font-size:11px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          opacity:.55;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Created:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ${
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                code.created_at
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ? new Date(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      code.created_at,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ).toLocaleString()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  : "Unknown"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          `;

        codeList.appendChild(card);
      });
    } catch (error) {
      console.error("Admin code list error:", error);

      codeList.innerHTML = `
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div style="
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          padding:14px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              color:#ff7777;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Unable to load codes.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              `;
    }
  }
  createButton.addEventListener("click", async () => {
    const code = codeInput.value.trim();

    const reward = Number(rewardInput.value);

    const limit = Number(limitInput.value);

    if (!code) {
      status.textContent = "Enter a code.";

      return;
    }

    if (!Number.isFinite(reward) || reward <= 0) {
      status.textContent = "Enter a valid Kash reward.";

      return;
    }

    if (!Number.isInteger(limit) || limit <= 0) {
      status.textContent = "Enter a valid redemption limit.";

      return;
    }

    createButton.disabled = true;

    createButton.textContent = "Creating...";

    status.textContent = "";
    try {
      const { data, error } = await supabaseClient.rpc(
        "admin_create_kash_code",
        {
          p_code: code,
          p_reward_kash: reward,
          p_max_redemptions: limit,
        },
      );

      if (error) {
        console.error("Admin code error:", error);

        status.textContent = error.message || "Unable to create code.";

        return;
      }

      if (!data || data.success !== true) {
        status.textContent = data?.message || "Unable to create code.";

        return;
      }

      status.textContent = `Created ${data.code} — ${Number(data.reward_kash).toLocaleString()} Kash — ${data.max_redemptions} uses.`;

      codeInput.value = "";
      rewardInput.value = "";
      limitInput.value = "";

      await loadCodes();
    } catch (error) {
      console.error("Admin code error:", error);

      status.textContent = error.message || "Unable to create code.";
    } finally {
      createButton.disabled = false;

      createButton.textContent = "+ Create Code";
    }
  });

  loadCodes();
});
