// ========================================
// KYDNO KORE - REDEEM CODES SYSTEM
// ========================================

window.kydnoRedeemCodes = {

    async redeemCode(code) {

            if (!code || !code.trim()) {
                        return {
                                        success: false,
                                                        message: "Enter a code."
                                                                    };
                                                                            }

                                                                                    const cleanCode = code.trim();

                                                                                            try {

                                                                                                        const { data, error } =
                                                                                                                        await supabaseClient.rpc(
                                                                                                                                            "redeem_kash_code",
                                                                                                                                                                {
                                                                                                                                                                                        input_code: cleanCode
                                                                                                                                                                                                            }
                                                                                                                                                                                                                            );
                                                                                                                                                                                                                            

                                                                                                                                                                                                                                        if (error) {
                                                                                                                                                                                                                                                        console.error("Redeem code error:", error);

                                                                                                                                                                                                                                                                        return {
                                                                                                                                                                                                                                                                                            success: false,
                                                                                                                                                                                                                                                                                                                message: error.message || "Unable to redeem code."
                                                                                                                                                                                                                                                                                                                                };
                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                        if (!data || data.success !== true) {
                                                                                                                                                                                                                                                                                                                                                                    return {
                                                                                                                                                                                                                                                                                                                                                                            success: false,
                                                                                                                                                                                                                                                                                                                                                                                    message: data?.message || "Invalid code."
                                                                                                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                        return {
                                                                                                                                                                                                                                                                                                                                                                                            success: true,
                                                                                                                                                                                                                                                                                                                                                                                                data: data
                                                                                                                                                                                                                                                                                                                                                                                                };
                                                                                                                                                                                                                                                                                                                                                        

                                                                                                                                                                                                                                                                                                                                                                                                            } catch (error) {

                                                                                                                                                                                                                                                                                                                                                                                                                        console.error("Redeem code error:", error);

                                                                                                                                                                                                                                                                                                                                                                                                                                    return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    success: false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    message: error.message || "Unable to redeem code."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // ========================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // CODES POPUP
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // ========================================

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            document.addEventListener("DOMContentLoaded", () => {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const codesButton =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        document.getElementById("codes-button");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const codesPopup =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    document.getElementById("codes-popup");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const codesClose =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                document.getElementById("codes-popup-close");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const codesOverlay =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            document.querySelector(".codes-popup-overlay");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const codesInput =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        document.getElementById("codes-input");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (!codesButton || !codesPopup) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.warn("Kydno Codes popup elements not found.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Open Codes popup
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        codesButton.addEventListener("click", () => {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                codesPopup.classList.remove("hidden");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (codesInput) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    setTimeout(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    codesInput.focus();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }, 100);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Close with X
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (codesClose) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            codesClose.addEventListener("click", () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        codesPopup.classList.add("hidden");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Close by clicking outside
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (codesOverlay) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    codesOverlay.addEventListener("click", () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                codesPopup.classList.add("hidden");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Close with Escape
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    document.addEventListener("keydown", (event) => {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        event.key === "Escape" &&
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    !codesPopup.classList.contains("hidden")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        codesPopup.classList.add("hidden");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
// ========================================
// REDEEM CODE BUTTON
// ========================================

document.addEventListener("DOMContentLoaded", () => {

    const redeemButton =
            document.getElementById("codes-redeem-button");

                const codesInput =
                        document.getElementById("codes-input");

                            const codesMessage =
                                    document.getElementById("codes-message");

                                        if (!redeemButton || !codesInput || !codesMessage) {
                                                return;
                                                    }

                                                        redeemButton.addEventListener("click", async () => {

                                                                const code = codesInput.value.trim();

                                                                        if (!code) {
                                                                                    codesMessage.textContent = "Enter a code.";
                                                                                                return;
                                                                                                        }

                                                                                                                redeemButton.disabled = true;
                                                                                                                        redeemButton.textContent = "REDEEMING...";
                                                                                                                                codesMessage.textContent = "";

                                                                                                                                        const result =
                                                                                                                                                    await window.kydnoRedeemCodes.redeemCode(code);

                                                                                                                                                            if (result.success) {

                                                                                                                                                                        const reward =
                                                                                                                                                                                        result.data?.reward_kash ?? 0;

                                                                                                                                                                                                    codesMessage.textContent =
                                                                                                                                                                                                                    `Success! You received ${reward.toLocaleString()} Kash.`;

                                                                                                                                                                                                                                codesInput.value = "";

                                                                                                                                                                                                                                            // Refresh the displayed Kash balance if available
                                                                                                                                                                                                                                                        if (
                                                                                                                                                                                                                                                                        window.kydnoKash &&
                                                                                                                                                                                                                                                                                        typeof window.kydnoKash.loadBalance === "function"
                                                                                                                                                                                                                                                                                                    ) {
                                                                                                                                                                                                                                                                                                                    window.kydnoKash.loadBalance();
                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                        } else {

                                                                                                                                                                                                                                                                                                                                                    codesMessage.textContent =
                                                                                                                                                                                                                                                                                                                                                                    result.message || "Unable to redeem code.";

                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                    redeemButton.disabled = false;
                                                                                                                                                                                                                                                                                                                                                                                            redeemButton.textContent = "REDEEM CODE";

                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                });

