// ========================================
// KYDNO KORE - REDEEM CODES SYSTEM
// ========================================

window.kydnoRedeemCodes = {

    async redeemCode(code) {

            if (!code || !code.trim()) {
                        return {
                                        success: false,
                                                        message: "Enter a code."
                                                                    };
                                                                            }

                                                                                    const cleanCode = code.trim();

                                                                                            try {

                                                                                                        const { data, error } =
                                                                                                                        await supabaseClient.rpc(
                                                                                                                                            "redeem_kash_code",
                                                                                                                                                                {
                                                                                                                                                                                        input_code: cleanCode
                                                                                                                                                                                                            }
                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                        if (error) {
                                                                                                                                                                                                                                                        console.error("Redeem code error:", error);

                                                                                                                                                                                                                                                                        return {
                                                                                                                                                                                                                                                                                            success: false,
                                                                                                                                                                                                                                                                                                                message: error.message || "Unable to redeem code."
                                                                                                                                                                                                                                                                                                                                };
                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                        return {
                                                                                                                                                                                                                                                                                                                                                                        success: true,
                                                                                                                                                                                                                                                                                                                                                                                        data: data
                                                                                                                                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                                                                                                                                            } catch (error) {

                                                                                                                                                                                                                                                                                                                                                                                                                        console.error("Redeem code error:", error);

                                                                                                                                                                                                                                                                                                                                                                                                                                    return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    success: false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    message: error.message || "Unable to redeem code."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // ========================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // CODES POPUP
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // ========================================

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            document.addEventListener("DOMContentLoaded", () => {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const codesButton =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        document.getElementById("codes-button");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const codesPopup =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    document.getElementById("codes-popup");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const codesClose =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                document.getElementById("codes-popup-close");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const codesOverlay =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            document.querySelector(".codes-popup-overlay");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const codesInput =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        document.getElementById("codes-input");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (!codesButton || !codesPopup) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.warn("Kydno Codes popup elements not found.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Open Codes popup
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        codesButton.addEventListener("click", () => {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                codesPopup.classList.remove("hidden");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (codesInput) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    setTimeout(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    codesInput.focus();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }, 100);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Close with X
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (codesClose) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            codesClose.addEventListener("click", () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        codesPopup.classList.add("hidden");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Close by clicking outside
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (codesOverlay) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    codesOverlay.addEventListener("click", () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                codesPopup.classList.add("hidden");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Close with Escape
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    document.addEventListener("keydown", (event) => {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        event.key === "Escape" &&
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    !codesPopup.classList.contains("hidden")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        codesPopup.classList.add("hidden");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Open Kydno Kore Codes popup
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    document.addEventListener("click", function (event) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const codesButton = event.target.closest("#codes-button");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const codesPopup = document.getElementById("codes-popup");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (!codesButton || !codesPopup) return;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    codesPopup.classList.remove("hidden");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
